// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYVeK9ZpGnRP8xwIprDM9oRoWkhKlNCHc',
    appId: '1:723271946889:web:1b0516666ef7bba3e2ac58',
    messagingSenderId: '723271946889',
    projectId: 'restaurante-crr',
    authDomain: 'restaurante-crr.firebaseapp.com',
    storageBucket: 'restaurante-crr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmfpRRJ3mGK5k6vtoASEelVFQkqnJwpXw',
    appId: '1:723271946889:android:c5fe332cffc4daa4e2ac58',
    messagingSenderId: '723271946889',
    projectId: 'restaurante-crr',
    storageBucket: 'restaurante-crr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8oiRBwoqXnBlRS9jxjk3MTkgWP2ySRzI',
    appId: '1:723271946889:ios:0ff2c6149434dadae2ac58',
    messagingSenderId: '723271946889',
    projectId: 'restaurante-crr',
    storageBucket: 'restaurante-crr.appspot.com',
    iosBundleId: 'com.example.empty',
  );
}
